"""
Signal journal: logs every signal generated by the pipeline to SQLite, including
inputs (regime, confidence, bias) and outcome (filled in later via update_outcome).

Two-phase logging:
  1. log_signal()    - called immediately when a signal is generated (outcome unknown)
  2. update_outcome() - called after the trade resolves (target/stop/timeout hit)

This separation mirrors real trading: you know the signal at entry time, but the
outcome only at exit time. The journal is the ground truth for performance reporting.
"""
import sqlite3
import time
from datetime import datetime, timezone
from typing import Optional


CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS signal_journal (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    generated_at    TEXT NOT NULL,
    timestamp_utc   INTEGER NOT NULL,
    session         TEXT,
    regime          TEXT,
    bias            TEXT NOT NULL,
    confidence      REAL NOT NULL,
    entry_zone_low  REAL,
    entry_zone_high REAL,
    invalidation    REAL,
    target          REAL,
    reasoning       TEXT,
    outcome         TEXT,
    outcome_pnl     REAL,
    outcome_logged_at TEXT
);
"""


class SignalJournal:
    def __init__(self, db_path: str):
        self.db_path = db_path
        self._init_db()

    def _connect(self):
        return sqlite3.connect(self.db_path)

    def _init_db(self):
        with self._connect() as conn:
            conn.execute(CREATE_TABLE_SQL)
            conn.commit()

    def log_signal(self, signal: dict) -> int:
        """
        Insert a new signal row. Returns the new row id (used later for update_outcome).
        signal is the dict from realtime/pipeline.py::generate_signal().
        """
        entry_zone = signal.get("entry_zone") or [None, None]
        targets = signal.get("targets") or [None]
        row = (
            signal.get("generated_at", datetime.now(timezone.utc).isoformat()),
            int(signal.get("timestamp_utc", 0)),
            signal.get("session"),
            signal.get("regime"),
            signal["bias"],
            float(signal["confidence"]),
            entry_zone[0],
            entry_zone[1] if len(entry_zone) > 1 else None,
            signal.get("invalidation"),
            targets[0],
            signal.get("reasoning_summary"),
        )
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO signal_journal
                   (generated_at, timestamp_utc, session, regime, bias, confidence,
                    entry_zone_low, entry_zone_high, invalidation, target, reasoning)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
                row,
            )
            conn.commit()
            return cursor.lastrowid

    def update_outcome(self, row_id: int, outcome: str, pnl: Optional[float] = None):
        """
        Fill in trade outcome after it resolves. outcome: "target", "stop", "timeout", "cancelled".
        """
        with self._connect() as conn:
            conn.execute(
                """UPDATE signal_journal
                   SET outcome=?, outcome_pnl=?, outcome_logged_at=?
                   WHERE id=?""",
                (outcome, pnl, datetime.now(timezone.utc).isoformat(), row_id),
            )
            conn.commit()

    def fetch_all(self) -> list:
        with self._connect() as conn:
            rows = conn.execute("SELECT * FROM signal_journal ORDER BY id").fetchall()
        return rows

    def fetch_unresolved(self) -> list:
        """Returns all signals where outcome is still NULL (trade not yet closed)."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM signal_journal WHERE outcome IS NULL ORDER BY id"
            ).fetchall()
        return rows
